# Generated by Django 5.1.6 on 2025-02-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hortaliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField()),
                ('Advertencias', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='historicoprecios',
            name='hortaliza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.hortaliza'),
        ),
    ]
