# Generated by Django 5.1.6 on 2025-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_hortaliza_historicoprecios_hortaliza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hortaliza',
            name='Advertencias',
        ),
        migrations.AddField(
            model_name='hortaliza',
            name='tiempoCosechaInvierno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hortaliza',
            name='tiempoCosechaVerano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hortaliza',
            name='advertencias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
